name: learnopengl
description: learnopengl.com for Dart
version: 1.0.1
homepage: https://github.com/sansuido/learnopengl
repository: https://github.com/sansuido/learnopengl

environment:
  sdk: '>=2.14.1 <3.0.0'

dependencies:
  ffi: ^1.1.2
  glew: ^1.0.1
  glfw3: ^1.0.0
  image: ^3.0.2
  sdl2: ^1.0.12
  vector_math: ^2.1.0
